# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Jboss-app
  
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk1.8.0_202'
    mavenVersionOption: 'Path'
    mavenDirectory: 'C:\Program Files\apache-maven-3.3.3'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    goals: 'package'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'C:\agent\_work\1\s\target'
    Contents: '*.war'
    TargetFolder: 'D:\jboss-eap-7.4.0.Beta\jboss-eap-7.4\standalone\deployments'
    preserveTimestamp: true
